feat: 회원가입, header작업
hyemin065/todo pull request #2
Opened 2023-11-06 08:21 UTC by hyemin065

작업내용 🛠
- 회원가입 api 작업
- 유효성 검사
- header css

체크 리스트 ✅
구현한 기능이 잘 동작하는지 직접 브라우저에서 확인/테스트 했습니다.

스크린샷 🌠
N/A

참고사항 📖
N/A

2023-11-06 14:19 UTC, AnJuhwan requested changes
고생하셨습니다.
이거는 저도 협업하면서 느끼는거지만 내가 짠 컴포넌트들이 다른사람들이 쓰려고할 때 상황에 맞게 쓸 수 있는지, 한눈에 들어오는 컴포넌트인지, 어떤 의도를 가지고 있는 프로퍼티 & 네이밍 인지 생각하며서 컴포넌트를 짜신다면 더욱 좋아지실 거 같아요

2023-11-06 14:19 UTC, AnJuhwan commented on src/api/axiosPublic.ts
> +};
💊 console.log 는 사용 후 지워주세요!
💊 axios 같은 경우는 instance로 빼서 사용하는 걸 추천드립니다.
💬 저 같은 경우는 post에서 받는 그대로의 params을 내려줘서 그대로 사용합니다.
    타입도 그렇게 설정을 해야겠죠?
```
export const joinApi = async (params: JoinType) => {
  const res = await axios.post('http://localhost:8088/api/auth/signUp',params)
}
```
```
type JoinType = {
  userId: string;
  password: string;
  email: string;
  name: string;
}
```
이렇게되면 좀 더 직관적이지 않을까 생각합니다.

❗️error에 response.data가 없을 수도 있을 때 오류가 날 거 같습니다.
```
catch (error: any) {
    throw new Error(error?.response?.data?.message || error);
 }
```
에러에 data을 안내려줬을때도 생각을해서 error자체를 뱉도록 하는게 좋아보입니다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Button.tsx
> +      {children}
❓ styled components을 사용하는데 className을 쓰신 이유가 있는지 궁금합니다.
 
 💊 이거는 협업할 때의 얘기이지만 만약에 디자인 시스템이 있는대도 불구하고 가끔씩 다른 컬러를 써야 할 때가 온다면 `color` & `background-color` & `width` & styles 정도는 props로 내려주도록 해줘야 하지 않을까 생각합니다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Button.tsx
❗️ `components` 안에 파일들이 저런식으로 폴더의 묶음없이 계속된다면 유지보수가 아주 어려워질거로 생각합니다.
     페이지 or 기능 별로 폴더를 묶어주세요!

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/FormGroup.tsx
💊  `FormGroup` 이라는 컴포넌트의 이름은 직관성을 떨어트리는거 같아요.
      만든이는 알겠지만 처음온사람이 봤을 때는 `FormGroup` 이 무슨일을 하는 컴포넌트인지 모를 거 같습니다.
      제가 코드를 보고 추측하기로는 `Input` 에 관한 컴포넌트 같은데 그냥 `BasicInput` or `ServiceInput` 이런식으로 
      네이밍을 하시는건 어떠실까요? 
      
💬 저희회사 같은 경우는 `TriveInput` 이런식으로 네이밍을 짓고 있습니다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/FormGroup.tsx
> +};
❓ `id` & `label` & `onChange`을 필수값으로 처리한 이유가 있으실까요?

💊 `id` & `label` & `onChange` 옵셔널로 처리해도 괜찮지 않을까요?

💊 `label` 은 필수값이라면 불편할 거 같아요.
     실제로 협업을 하게되면 `label`이 들어있는 `input`이 있기도 하고 없기도 합니다.
     만약에 이렇다하면 `label`이 필수값이라면 불편하지 않을까요..?

💬 저희는 `LabelInput` , `Input` 따로 디자인별로 빠져있어요

💊 `Props - type` 타입은 Input Type의 있는 Type을 따라가는게 좋을 거 같아요. 
     `Input` 안에 있는 각각의 프로퍼티 타입을 추출할 수 있는 방법이 있습니다.
     찾아보시면 좋을 거 같아요.

💊 `onChange` 의 파라미터 네이밍은 `e 또는 event` 라고 명시해주는게 좋을 거 같아요.
     `value` 라고한다면 다른사람이 헷갈릴 수 있지 않을까 생각합니다.
     
💊 `errorMessage` 한 컴포넌트안에 많은 기능을 제공하는건 좋지 않아요.
     `errorMessage` 에러메세지를 표시해주는 컴포넌트는 따로 빼줍시다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/FormGroup.tsx
> +    </FormInputGroup>
💊 컴포넌트를 작성할 때는 그 컴포넌트의 맞는 아주 작은 단위부터 작성해야합니다.
     한 컴포넌트안에 많은 기능을 제공하는건 안좋은 패턴같아요.
     `atomic pattern` 한번 찾아보시면 좋을 거 같습니다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Header.tsx
> +          <NavLink to='/login'>Sign In</NavLink>
💊 `NavLink` 컴포넌트도 `Link` 컴포넌트화 시켜서 사용하면 더 보기 좋을 거 같아요.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Header.tsx
> +  }
💊 사용하지 않는 코드는 지워주세요~

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Input.tsx
> +  return <StyledInput className={className} type={type} id={id} value={value} onChange={onChange} />;
❓ styled components을 사용하는데 `className` 을 사용하신 이유가 있으실까요?

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Input.tsx
> +  type?: string;
💊 위에서 말씀드렸지만 `Input` 안에 있는 `type` 프로퍼티의 `Type`을 추출해서 타입지정해주는게 좋아보입니다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +const emailRegEx = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
💬 이런 정규식 같은 경우는 저같은 경우는  `utils/regex/index.ts` 에 넣어서 보관하고 있습니다.
만약에 다른대에서 쓰인다면 따로 빼는게 좋아보입니다!

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +  });
💊 `JoinType` 은 아까 API쪽에서 Type을 본거 같은데 실제로 `Body`에 들어가는 Type과 State의 Type 이 다르다면 나눠주는게 좋아보입니다. (헷갈릴수도 있을 거 같아요)

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +  });
❓ 이렇게 `errorMessage`을 나눠놓은것은 모든 에러를 표시해주기 위함이겠죠?
     `errorMessage.error` 는 무슨 용도인지 궁금합니다

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +    }
💊 이 부분은 유틸로 충분히 뺄 수 있을거 같아요.
     시도해봅시다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +    ) {
💊 이 부분은 위에서 체크하고 있는데 아래에서 또 체크하는 이유가 있을까요?
     이 코드들은 제거 할 수 있는 코드라고 생각해요!

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +        }
💊 `try catch` 문을 썼는데 `if (res)` 는 불필요한 코드가 아닐까 생각됩니다

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +  };
💊 API 실행할때는 인터넷이 느린 유저들을 위해서 `Loading` 같은 시각적인걸 보여주면 좋다고 생각해요

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +          <Button onClick={onClick}>회원가입</Button>
❗️ 인터넷이 느린 사람은 회원가입을 여러번 눌러서 함수가 여러변 실행될 수 도 있을거 같아요
     disabled로 막아주는게 필요해보입니다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Join.tsx
> +        </form>
💊 폼이 너무 많아지니까 보기 힘들어지는거 같아요 이런 코드는 컴포넌트로 한번 더 빼면 어떨까 싶어요

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/Login.tsx
> +        <Button onClick={onClick}>로그인</Button>
💊 로그인도 `disabled` 걸어주는게 좋아보입니다.
     `Loading`도 추가해주시면 좋을 거 같아요.

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/SignUp.tsx
> +const emailRegEx = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
💊 요기서또 쓴다면 따로 파일로 빼는게 좋아보이네요~!

2023-11-06 14:19 UTC, AnJuhwan commented on src/components/SignUp.tsx
❓ `SignUp` 컴포넌트와 `Join` 컴포넌트는 다른 컴포넌트인가요? 똑같은 코드같은..?
     일단 이 파일은 따로 리뷰 안하겠습니다.

2023-11-06 14:19 UTC, AnJuhwan commented on src/type/type.ts
> +};
💊 위에서 말씀드렸다싶이 `Body Type` , `State Type` 따로 타입을 가져가는게 맞다고 생각합니다.

2023-11-07 01:20 UTC, hyemin065 commented on src/api/axiosPublic.ts
> +};
Axios instance는 interceptor만들때 같이 만들 예정입니다 🙂

post에서 받는 그대로를 넣어주려면 객체이름이 안맞아서 받아서 변경해준건데 보낼때 미리 변경해서 보내면 되겠네요! 에러도 말해주신대로 변경하는게 좋을것같네요 감사합니다

2023-11-07 01:28 UTC, hyemin065 commented on src/components/Button.tsx
> +      {children}
저는 컴포넌트내에서 css만을 위한 프롭스를 늘리기보다 디자인시스템내에서의 디자인은 컴포넌트에서 클래스로 만들어두고 다른 디자인이 생긴다면 각각의 페이지에서만 스타일을 덮어써주는게 더 나을거같다는 생각입니다
그래서 클래스네임을 넘겨줬습니다

2023-11-07 01:36 UTC, hyemin065 commented on src/components/Button.tsx
네 저도 폴더별로 묶는게 좋을것같아요 수정할게요

2023-11-07 01:37 UTC, hyemin065 commented on src/components/FormGroup.tsx
👍

2023-11-07 01:46 UTC, hyemin065 commented on src/components/FormGroup.tsx
> +    </FormInputGroup>
감사합니다👍

2023-11-07 02:03 UTC, hyemin065 commented on src/components/FormGroup.tsx
> +};
작은 프로젝트라 label이 없는 경우를 생각하지 않았는데 참고해서 수정해보겠습니다

2023-11-07 02:05 UTC, hyemin065 commented on src/components/Join.tsx
> +const emailRegEx = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
저도 utils로 따로빼놨다가 다른곳에서 쓰일일이 없어서 다시 합쳐놨습니다 다른프로젝트를 한다면 저도 따로 빼놓을것같아요!

2023-11-07 02:06 UTC, hyemin065 commented on src/components/Join.tsx
> +  });
에러를 나눠놓은 이유는 각각의 에러를 각 인풋 하단에 보여주기 위해 사용했고 마지막 errorMessage.error는 api를 보낸후 받아온 에러를 표시하기위해 만들었습니다

2023-11-07 02:09 UTC, hyemin065 commented on src/components/Join.tsx
> +        }
const res = await joinApi(joinValue); 에서 값을 받아온 뒤에 setJoinSuccess를 실행하기 위해 사용했습니다

2023-11-07 02:09 UTC, hyemin065 commented on src/components/Join.tsx
> +  };
네 참고할게요~!

2023-11-07 02:12 UTC, hyemin065 commented on src/components/Join.tsx
> +        </form>
❓FormGroup들을 합쳐서 따로 컴포넌트를 만들라는 말씀이신가요? 그럼 만들게 된 컴포넌트안에서 또 보기 힘들어지는것 아닌가요??  제가 다르게 이해했으면 댓글 부탁드립니다

2023-11-07 02:14 UTC, hyemin065 commented on src/components/SignUp.tsx
> +const emailRegEx = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
signUp 파일은 삭제할예정입니다 Join파일에 문제가있어서 만들어놓고 삭제를 안했네요 😿😿

2023-11-07 02:48 UTC, AnJuhwan commented on src/api/axiosPublic.ts
> +};
💬 Axios instance는 미리 만들어주시는게 좋아보입니다! 
    interceptor 할 때 만들게 되면 혜민님도 두번작업하는 것이 되는것이고
    리뷰하는 사람 입장에서도 `instance 만들기 전의 코드` & `instance 만든 후 코드` 비교하면서 다시 한번 리뷰를
    해야하니 미리 만들어두시는게 생산성을 위해 더 좋지 않을까 생각합니다

2023-11-07 02:51 UTC, AnJuhwan commented on src/components/Button.tsx
> +      {children}
💬 위에서 말씀한 대로라면 className으로 덮어주신다고한다면 `styled components` 의 장점이 없어지는거 같습니다.
    styled components의 장점은 **style에 props을 넘겨줘서 핸들링 할 수 있다는 것** & 이미 만들어진 **`Input`등을 한번 더 
    감싸서 `style custom`** 할 수 있다고 알고있는데 className으로 덮어주는걸 선호하신다면 css 사용이 더 맞다고 생각듭니다.

2023-11-07 02:53 UTC, AnJuhwan commented on src/components/Join.tsx
> +        }
💊 if (res) 을 쓰지 않아도 잘 실행될것으로 예상됩니다!

2023-11-07 02:57 UTC, AnJuhwan commented on src/components/Join.tsx
> +        </form>
💬 네 이해하신게 맞습니다.
   위에 코드까지 첨부해드릴걸 그랬네요. 
   위에코드를 간략하게 말씀드리자면  예시: ` isData ? <>...</>  : <form> .... </form>` 이렇게 되어있는데 이런 코드보단
   ` isData ? <>회원가입축하</> : <SignForm />` 이 더 깔끔하지 않을까 생각이 듭니다.
   그렇게 된다면 다른사람이 볼 때 한눈에도 `SignForm` 네이밍만 봤을때도 짐작가는 코드이지 않나 생각이 듭니다.

2023-11-07 04:31 UTC, hyemin065 commented on src/components/Button.tsx
> +      {children}
제가 헷갈리게 말씀드렸네요
디자인시스템상에 있는 success버튼 디자인이나 error버튼 디자인은 미리 만들어두고 className을 sccuess, error 이런식으로 넘겨줘서 스타일이 적용되게 할거고 덮어쓴다는 뜻은 해당 styled-component로 덮어쓴다는 뜻이였습니다
const TitleButton = styled(Button) 이런식으로 기존 default button디자인에 새로운 디자인을 입힌 style을 만들어서 사용한다는 뜻이였습니다

2023-11-07 04:34 UTC, hyemin065 commented on src/api/axiosPublic.ts
> +};
아! 저는 interceptor 만들때 그안에 instance를 만들어두려고했어서 로그인작업후에 accessToken을 넘길때 interceptor, instance를 만들어야겠다고 생각했습니다

근데 instance는 interceptor와 별개로 빼서 만들어야겠네요!

2023-11-07 04:38 UTC, hyemin065 commented on src/components/Join.tsx
> +        </form>
이해했습니다 생각해보니 그런식으로 보는게 더 깔끔할것 같네요

2023-11-07 04:50 UTC, AnJuhwan commented on src/components/Button.tsx
> +      {children}
이해했습니다 설명 감사합니다! 👍👏

2023-11-11 14:22 UTC, AnJuhwan approved these changes
수고하셨습니다.

2023-11-11 14:22 UTC, AnJuhwan commented on src/components/atoms/Button.tsx
> +};
❓`isLoading` 이라는 props는 받고있는데 disabled 시키는 프로퍼티는 없는거 같네요..?
    혹시 제가 놓친게 있나요..? `disabled` 하는 코드는 없는거 같아요.

2023-11-11 14:22 UTC, AnJuhwan commented on src/components/atoms/Input.tsx
> +};
❓`id`을 특별히 넣어주시는 이유가 있으실까요?!
💬 음 이건 갑자기 생각이 든거지만 `input`컴포넌트도 disabled을 넣어줘야 되나..?
     라는 갑자기 의문점이 생기네요.. 어떻게 생각하시나요? (자유롭게 얘기해주세요)

2023-11-11 14:22 UTC, AnJuhwan commented on src/components/molecules/InputGroup.tsx
> +`;
💊 이런`ErrorMessage` 같은 경우는 다른곳에서도 쓰일 수 있으니 컴포넌트로 빼는건 어떠신가요?

2023-11-11 14:22 UTC, AnJuhwan commented on src/components/molecules/InputGroup.tsx
💊 파일 이름만 봤을 때는 어떤 컴포넌트인지 모를거 같아요 (제가 이름만 봤을때는 Input 몇개가 모여있는 그룹 컴포넌트인가..?) 생각이 듭니다.

💊 `InputLabel` 이런식으로 더 명확한 컴포넌트 이름으로 바꿔보시는건 어떠실까요? 

💊 ErrorMessage는 따로 넣지 않는게 좋다고 생각합니다. 컴포넌트 이름을 짓기 너무 어려워져요 (직관성이 떨어짐)
    하지만 이런경우는 있어도 되겠죠.
    무조건 입력되야하는 InputComponents 라면 `RequiredInputLabel` 이런식으로 짓게 되면 컴포넌트 이름만 보고
    무슨 동작을 할지 유추가 되니까요

2023-11-11 14:22 UTC, AnJuhwan commented on src/components/molecules/InputGroup.tsx
> +      {errorMessage !== '' && <ErrorMessage>{errorMessage}</ErrorMessage>}
💊 저는 개인적으로 `errorMessage` 까지 컴포넌트에 껴있는건 별로라 생각하는데..
     어떻게 생각하시나요..?
     
     이유 : `errorMessage` 까지 안에 넣어버리게 되면 컴포넌트 네이밍이 너무 
     애매해지는 문제가 생기는거 같아요.
     정말 예외적으로 value값이 입력이 안되었거나하면 입력하라는 `errorMessage`
     정도는 네이밍이 `RequiredInputLabel` 명확해질거 같은데 errorMessage가
     포함된 네이밍으로는 `ErrorWithInputLabel` 라고 지어도 무슨 컴포넌트인지 잘
     모를 수 있을거 같다는 생각이 듭니다.

2023-11-11 14:22 UTC, AnJuhwan commented on src/pages/join/Join.tsx
> +`;
💊 `ErrorText` 라는 컴포넌트를 만들면 여러군대에서 많이 재사용이 가능할 거 같습니다

2023-11-11 14:22 UTC, AnJuhwan commented on src/components/atoms/Input.tsx
> +  type?: 'button' | 'email' | 'file' | 'number' | 'password' | 'search' | 'submit' | 'tel' | 'text';
❗️input의 타입은 용도에 맞게 타입만 지정해주세요.
   `button & file & submit` 이런 타입은 맞지 않다고 생각합니다.

2023-11-13 09:28 UTC, hyemin065 commented on src/components/molecules/InputGroup.tsx
> +`;
현재 에러메세지는 컴포넌트로 뺐는데 저 코드가 예전꺼같네요..? 제 현재코드에선 저코드가 보이지않아요🤔🥲

2023-11-13 09:31 UTC, hyemin065 commented on src/components/atoms/Input.tsx
> +};
라벨을 클릭해도 input에 포커스가 생기게 하기 위해서 id를 넣었습니다!

현재 input을 쓰는곳에 버튼이 항상 쓰여서 버튼만 disabled 처리해주면 되지않을까요??

2023-11-13 10:11 UTC, hyemin065 commented on src/pages/join/Join.tsx
> +`;
이미 컴포넌트로 빼서 작업했습니다 👍

2023-11-13 10:13 UTC, hyemin065 commented on src/components/molecules/InputGroup.tsx
> +      {errorMessage !== '' && <ErrorMessage>{errorMessage}</ErrorMessage>}
저는 input과 error 메세지까지 하나의 세트라고 생각해서 한 컴포넌트안에 넣었는데 분리하는게 좋을지 생각해볼게요! 의견 감사합니다

2023-11-13 10:13 UTC, hyemin065 commented on src/components/molecules/InputGroup.tsx
네이밍 고민을 좀 더 해볼게요

2023-11-13 10:15 UTC, hyemin065 commented on src/components/atoms/Button.tsx
> +};
이 코드는 예전코드라 현재는 disabled={isLoading} isLoading이 true일때 disabled 처리 되게 되어있습니다~

2023-11-13 10:24 UTC, merged